In [1]:
import pandas as pd

df = pd.read_csv("gamedata1.csv")
df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,imdbRating,imdbVotes,imdbID
0,Red Dead Redemption II,2018,M,26 Oct 2018,NaN,"Action, Adventure, Crime, Drama, Western",NaN,"Dan Houser, Michael Unsworth, Rupert Humphries...","Benjamin Byron Davis, Roger Clark, Rob Wiethof...",Amidst the decline of the Wild West at the tur...,"English, Spanish, Polish, German, French, Ital...","USA, UK, Canada, India",19 wins & 24 nominations.,https://m.media-amazon.com/images/M/MV5BMThiMG...,9.7,"24,437",tt6161168
1,The Last of Us,2013,M,14 Jun 2013,NaN,"Action, Adventure, Drama, Horror, Sci-Fi, Thri...","Neil Druckmann, Bruce Straley",Neil Druckmann,"Ashley Johnson, Troy Baker, Hana Hayes, Jeffre...","In a hostile, post-pandemic world, Joel and El...","English, Portuguese",USA,48 wins & 19 nominations.,https://m.media-amazon.com/images/M/MV5BMTkzMz...,9.7,"51,602",tt2140553
2,The Witcher 3: Wild Hunt,2015,M,19 May 2015,NaN,"Action, Adventure, Drama, Fantasy, Romance",Konrad Tomaszkiewicz,"Marcin Blacha (lead writer), Borys Pugacz-Mura...","Doug Cockle, Denise Gough, Jo Wyatt, Jaimi Bar...",A monster hunter for hire embarks on an epic j...,"English, Polish",Poland,18 wins & 15 nominations.,https://m.media-amazon.com/images/M/MV5BYjY3OD...,9.7,"21,572",tt2993508
3,God of War,2018,M,20 Apr 2018,NaN,"Action, Adventure, Drama, Fantasy",Cory Barlog,"Matthew Sophos, Richard Zangrande Gaubert, Cor...","Christopher Judge, Sunny Suljic, Jeremy Davies...","After wiping out the gods of Mount Olympus, Kr...","English, Norse, Old",USA,31 wins & 26 nominations.,https://m.media-amazon.com/images/M/MV5BMmVjMz...,9.6,"18,805",tt5838588
4,The Legend of Zelda: Ocarina of Time,1998,E,23 Nov 1998,NaN,"Action, Adventure, Fantasy","Eiji Aonuma, Yoshiaki Koizumi, Shigeru Miyamot...","Tôru Ôsawa (script), Kensuke Tanabe (script), ...","Nobuyuki Hiyama, Fujiko Takimoto, Jun Mizusawa...",A young Hylian boy discovers that his destiny ...,English,Japan,11 wins & 2 nominations.,https://m.media-amazon.com/images/M/MV5BZjc3Mm...,9.6,"7,301",tt0184666
5,Mass Effect 2,2010,M,26 Jan 2010,NaN,"Action, Adventure, Sci-Fi",Casey Hudson,"John Dombrow (additional writing), Chris Heple...","Shohreh Aghdashloo, Maggie Baird, Adam Baldwin...",After being revived from death and having to j...,English,"USA, Canada",16 wins & 32 nominations.,https://m.media-amazon.com/images/M/MV5BY2FjYW...,9.5,"17,949",tt1540125
6,Grand Theft Auto V,2013,M,17 Sep 2013,NaN,"Action, Adventure, Crime, Drama",Rod Edge,"Dan Houser, Rupert Humphries, Michael Unsworth...","Shawn Fonteno, Ned Luke, Steven Ogg, Gerald 'S...",Three very different criminals team up for a s...,"English, Spanish, Mandarin, Russian, Korean, P...","UK, USA, Canada, India, Hong Kong, China",12 wins & 28 nominations.,https://m.media-amazon.com/images/M/MV5BZTI4YW...,9.5,"51,833",tt2103188
7,Metal Gear Solid,1998,M,21 Oct 1998,NaN,"Action, Adventure, Drama, Sci-Fi, Thriller",Hideo Kojima,"Hideo Kojima, Tomokazu Fukushima","Akio Ôtsuka, Banjô Ginga, Kyôko Terase, Hiromi...",A crack government anti-terrorist squad takes ...,Japanese,Japan,1 win & 5 nominations.,https://m.media-amazon.com/images/M/MV5BNDQ2ZD...,9.6,"10,784",tt0180825
8,Uncharted 4: A Thief's End,2016,T,10 May 2016,NaN,"Action, Adventure, Drama, Romance, Thriller","Neil Druckmann, Bruce Straley","Neil Druckmann, Josh Scherr, Tom Bissell (addi...","Nolan North, Troy Baker, Richard McGonagle, Em...",Thrown back into the dangerous underworld he'd...,"English, Spanish, Italian, Portuguese",USA,29 wins & 27 nominations.,https://m.media-amazon.com/images/M/MV5BODBhMz...,9.5,"22,793",tt3334704
9,Star Wars: Knights of the Old Republic,2003,T,18 Jul 2003,NaN,"Action, Adventure, Fantasy, Romance, Sci-Fi",Casey Hudson,"David Gaider, Michael Gallo (manual), Drew Kar...","Jennifer Hale, Raphael Sbarge, Rafael Ferrer, ...","A republic soldier, training to become a Jedi ...",English,"USA, Canada",4 wins & 3 nominations.,https://m.media-amazon.com/images/M/MV5BN2YwNj...,9.5,"7,759",tt0356070
10,Final Fantasy VII,1997,T,07 Sep 1997,NaN,"Action, Adventure, Fantasy, Sci-Fi","Yoshinori Kitase, Yasushi Matsumura, Masato Ya...","Kazushige Nojima (story), Yoshinori Kitase (st...",NaN,A former soldier from an evil company joins a ...,"Japanese, English",Japan,2 wins & 3 nominations.,https://m.media-amazon.com/images/M/MV5BMGMxZD...,9.5,"9,001",tt0208155
11,Chrono Trigger,1995,NaN,22 Aug 1995,NaN,"Animation, Action, Adventure","Yoshinori Kitase, Akihiko Matsui, Takashi Tokita",Masato Kato (story),NaN,"Crono, a young boy, is thrust to adventure by ...","Japanese, English",Japan,NaN,https://m.media-amazon.com/images/M/MV5BNzc2Nz...,9.3,"1,657",tt0210613
12,The Elder Scrolls V: Skyrim,2011,M,11 Nov 2011,NaN,"Action, Adventure, Fantasy, Horror, Mystery, War","Todd Howard, Nick James Pearce","Emil Pagliarulo, Brian Chapin (writing), Jon P...","Max von Sydow, Christopher Plummer, Joan Allen...","After escaping execution, the last living Drag...",English,"USA, Australia",14 wins & 17 nominations.,https://m.media-amazon.com/images/M/MV5BYjlhNT...,9.4,"26,755",tt1814884
13,Mass Effect,2007,M,20 Nov 2007,NaN,"Action, Adventure, Sci-Fi",Casey Hudson,"Drew Karpyshyn (lead writer), Lukas Kristjanso...","Steven Barr, Kimberly Brooks, Keith David, Set...","In a technologically advanced future, an elite...",English,"USA, Canada",5 wins & 23 nominations.,https://m.media-amazon.com/images/M/MV5BNjE3MG...,9.2,"16,184",tt1073668
14,Grand Theft Auto: Vice City,2002,M,29 Oct 2002,NaN,"Action, Adventure, Crime, Drama","Marco Fernandez, Navid Khonsari","Dan Houser, James Worrall, Dan Houser (written...","Ray Liotta, William Fichtner, Tom Sizemore, De...","After being released from jail, Tommy Vercetti...","English, Spanish, Haitian, French","UK, USA, Austria",15 wins & 19 nominations.,https://m.media-amazon.com/images/M/MV5BYmIwZG...,9.2,"23,031",tt0314123
15,Mafia: The City of Lost Heaven,2002,M,29 Aug 2002,NaN,"Action, Crime, Drama, Thriller",Daniel Vávra,Daniel Vávra,"Michael Sorvino, William DeMeo, George DiCenzo...",You play a 1930s mobster as you act out your c...,"English, Czech, French, German, Italian, Spanish","Czech Republic, USA",2 nominations.,https://m.media-amazon.com/images/M/MV5BMzcwNT...,9.2,"5,297",tt0338221
16,Deus Ex,2000,M,22 Jun 2000,NaN,"Action, Mystery, Sci-Fi, Thriller",Warren Spector,"Sheldon Pacotti (dialogue), Austin Grossman (a...","Jay Anthony Franke, Brent Anderson, Ralph Barb...","In a dark cyberpunk future where poverty, dise...","English, French, Mandarin","USA, UK",1 win.,https://m.media-amazon.com/images/M/MV5BMWM4MD...,9.2,"2,932",tt0286585
17,Grim Fandango,1998,NaN,NaN,NaN,"Adventure, Comedy, Crime",Tim Schafer,"Eric Ingerson, Bret Mogilefsky, Tim Schafer, P...","Tony Plana, Maria Canals-Barrera, Alan Blumenf...",Manuel Calavera is a travel agent in The Land ...,"English, Spanish, Hungarian",USA,1 nomination.,NaN,9.0,"2,224",tt0177822
18,Elden Ring,2022,NaN,21 Jan 2022,NaN,"Action, Adventure, Fantasy",Hidetaka Miyazaki,George R.R. Martin,NaN,The game will transport players into a dark fa...,"Japanese, English",Japan,NaN,https://m.media-amazon.com/images/M/MV5BMTE3MG...,NaN,NaN,tt10562854
19,Metal Gear Solid 3: Snake Eater,2004,M,17 Nov 2004,NaN,"Action, Adventure, Crime, Mystery, Romance",Hideo Kojima,"Hideo Kojima (story), Hideo Kojima, Tomokazu F...","David Hayter, Suzetta Miñet, Jim Piddock, Heat...","In 1964, a U.S. government operative codenamed...",Japanese,Japan,2 nominations.,https://m.media-amazon.com/images/M/MV5BNzhlND...,9.5,"9,271",tt0365498
20,Grand Theft Auto: San Andreas,2004,M,26 Oct 2004,NaN,"Action, Adventure, Comedy, Crime",Navid Khonsari,"Dan Houser, James Worrall, DJ Pooh, James Worr...","Young Maylay, Faizon Love, Yolanda 'Yo-Yo' Whi...","A family tragedy prompts gangster Carl ""CJ"" Jo...","English, Spanish, German","UK, USA, France, Germany, Denmark, Hungary, Be...",6 wins & 12 nominations.,https://m.media-amazon.com/images/M/MV5BMTdkZD...,9.4,"35,019",tt0383385
21,Red Dead Redemption,2010,M,18 May 2010,NaN,"Action, Adventure, Crime, Drama, Western","Rod Edge, John Zurhellen","Dan Houser, Michael Unsworth, Christian Cantam...","Rob Wiethoff, Josh Blaylock, Sophia Marzocchi,...",A former outlaw is forced by the federal gover...,"English, Spanish, French, Cantonese, German","USA, UK, Canada",25 wins & 22 nominations.,https://m.media-amazon.com/images/M/MV5BZmYwNj...,9.5,"23,312",tt1479962
22,Batman: Arkham City,2011,T,18 Oct 2011,NaN,"Action, Adventure, Crime, Drama, Fantasy, Myst...",Sefton Hill,"Bob Kane (character created by: Batman), Paul ...","Carlos Alazraqui, Dee Bradley Baker, Troy Bake...",When part of Gotham is turned into a private r...,English,"UK, USA",17 wins & 28 nominations.,https://m.media-amazon.com/images/M/MV5BZDE2ZD...,9.4,"26,880",tt1568322
23,The Legend of Zelda: Breath of the Wild,2017,E10+,03 Mar 2017,NaN,"Action, Adventure, Fantasy","Hidemaro Fujibayashi, Hiroki Hirano, Kentaro T...",Akihito Toda (screenplay advisor),"Kengo Takanashi, Yû Shimamura, Kôji Takeda, No...","After a century of hibernation, Link reawakens...","Japanese, English","USA, Japan",8 wins & 12 nominations.,https://m.media-amazon.com/images/M/MV5BZTI3OT...,9.4,"5,083",tt3253986
24,Uncharted 2: Among Thieves,2009,T,13 Oct 2009,NaN,"Action, Adventure, Fantasy, Horror, Mystery, T...","Amy Hennig, Bruce Straley","Amy Hennig, Neil Druckmann, Josh Scherr","Nolan North, Emily Rose, Claudia Black, Richar...","After being tracked down by Harry Flynn, Natha...","Tibetan, English, Nepali",USA,30 wins & 16 nominations.,https://m.media-amazon.com/images/M/MV5BZDk4ZG...,9.4,"21,540",tt1349460
25,Portal 2,2011,NaN,19 Apr 2011,NaN,"Action, Adventure, Comedy",Joshua Weier,"Chet Faliszek, Ted Kosmatka, Jay Pinkerton, Er...","Ellen McLain, Stephen Merchant, J.K. Simmons, ...","Many years after ""Portal,"" Chell reawakens at ...",English,USA,9 wins & 8 nominations.,https://m.media-amazon.com/images/M/MV5BMTQ1MD...,9.5,"8,256",tt1648163
26,Half-Life 2,2004,M,16 Nov 2004,NaN,"Action, Adventure, Sci-Fi, Thriller",David Speyrer,Marc Laidlaw,"Robert Guillaume, Robert Culp, Louis Gossett J...","Dr. Freeman is taken out of stasis by his ""emp...","English, Russian",USA,28 wins & 13 nominations.,https://m.media-amazon.com/images/M/MV5BNzEwND...,9.4,"14,580",tt0374692
27,Mass Effect 3,2012,M,06 Mar 2012,NaN,"Action, Adventure, Sci-Fi",Casey Hudson,"John Dombrow (senior writer), Sylvia Feketekut...","Jennifer Hale, Mark Meer, Kimberly Brooks, Rap...",Earth is under attack by a monstrous race of g...,English,Canada,8 wins & 14 nominations.,https://m.media-amazon.com/images/M/MV5BYzg0OG...,9.1,"13,999",tt1839558

In [3]:
df['Runtime'].drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [4]:
df1 = df.drop(columns=['Runtime'])
df1

,Title,Year,Rated,Released,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,imdbRating,imdbVotes,imdbID
0,Red Dead Redemption II,2018,M,26 Oct 2018,"Action, Adventure, Crime, Drama, Western",NaN,"Dan Houser, Michael Unsworth, Rupert Humphries...","Benjamin Byron Davis, Roger Clark, Rob Wiethof...",Amidst the decline of the Wild West at the tur...,"English, Spanish, Polish, German, French, Ital...","USA, UK, Canada, India",19 wins & 24 nominations.,https://m.media-amazon.com/images/M/MV5BMThiMG...,9.7,"24,437",tt6161168
1,The Last of Us,2013,M,14 Jun 2013,"Action, Adventure, Drama, Horror, Sci-Fi, Thri...","Neil Druckmann, Bruce Straley",Neil Druckmann,"Ashley Johnson, Troy Baker, Hana Hayes, Jeffre...","In a hostile, post-pandemic world, Joel and El...","English, Portuguese",USA,48 wins & 19 nominations.,https://m.media-amazon.com/images/M/MV5BMTkzMz...,9.7,"51,602",tt2140553
2,The Witcher 3: Wild Hunt,2015,M,19 May 2015,"Action, Adventure, Drama, Fantasy, Romance",Konrad Tomaszkiewicz,"Marcin Blacha (lead writer), Borys Pugacz-Mura...","Doug Cockle, Denise Gough, Jo Wyatt, Jaimi Bar...",A monster hunter for hire embarks on an epic j...,"English, Polish",Poland,18 wins & 15 nominations.,https://m.media-amazon.com/images/M/MV5BYjY3OD...,9.7,"21,572",tt2993508
3,God of War,2018,M,20 Apr 2018,"Action, Adventure, Drama, Fantasy",Cory Barlog,"Matthew Sophos, Richard Zangrande Gaubert, Cor...","Christopher Judge, Sunny Suljic, Jeremy Davies...","After wiping out the gods of Mount Olympus, Kr...","English, Norse, Old",USA,31 wins & 26 nominations.,https://m.media-amazon.com/images/M/MV5BMmVjMz...,9.6,"18,805",tt5838588
4,The Legend of Zelda: Ocarina of Time,1998,E,23 Nov 1998,"Action, Adventure, Fantasy","Eiji Aonuma, Yoshiaki Koizumi, Shigeru Miyamot...","Tôru Ôsawa (script), Kensuke Tanabe (script), ...","Nobuyuki Hiyama, Fujiko Takimoto, Jun Mizusawa...",A young Hylian boy discovers that his destiny ...,English,Japan,11 wins & 2 nominations.,https://m.media-amazon.com/images/M/MV5BZjc3Mm...,9.6,"7,301",tt0184666
5,Mass Effect 2,2010,M,26 Jan 2010,"Action, Adventure, Sci-Fi",Casey Hudson,"John Dombrow (additional writing), Chris Heple...","Shohreh Aghdashloo, Maggie Baird, Adam Baldwin...",After being revived from death and having to j...,English,"USA, Canada",16 wins & 32 nominations.,https://m.media-amazon.com/images/M/MV5BY2FjYW...,9.5,"17,949",tt1540125
6,Grand Theft Auto V,2013,M,17 Sep 2013,"Action, Adventure, Crime, Drama",Rod Edge,"Dan Houser, Rupert Humphries, Michael Unsworth...","Shawn Fonteno, Ned Luke, Steven Ogg, Gerald 'S...",Three very different criminals team up for a s...,"English, Spanish, Mandarin, Russian, Korean, P...","UK, USA, Canada, India, Hong Kong, China",12 wins & 28 nominations.,https://m.media-amazon.com/images/M/MV5BZTI4YW...,9.5,"51,833",tt2103188
7,Metal Gear Solid,1998,M,21 Oct 1998,"Action, Adventure, Drama, Sci-Fi, Thriller",Hideo Kojima,"Hideo Kojima, Tomokazu Fukushima","Akio Ôtsuka, Banjô Ginga, Kyôko Terase, Hiromi...",A crack government anti-terrorist squad takes ...,Japanese,Japan,1 win & 5 nominations.,https://m.media-amazon.com/images/M/MV5BNDQ2ZD...,9.6,"10,784",tt0180825
8,Uncharted 4: A Thief's End,2016,T,10 May 2016,"Action, Adventure, Drama, Romance, Thriller","Neil Druckmann, Bruce Straley","Neil Druckmann, Josh Scherr, Tom Bissell (addi...","Nolan North, Troy Baker, Richard McGonagle, Em...",Thrown back into the dangerous underworld he'd...,"English, Spanish, Italian, Portuguese",USA,29 wins & 27 nominations.,https://m.media-amazon.com/images/M/MV5BODBhMz...,9.5,"22,793",tt3334704
9,Star Wars: Knights of the Old Republic,2003,T,18 Jul 2003,"Action, Adventure, Fantasy, Romance, Sci-Fi",Casey Hudson,"David Gaider, Michael Gallo (manual), Drew Kar...","Jennifer Hale, Raphael Sbarge, Rafael Ferrer, ...","A republic soldier, training to become a Jedi ...",English,"USA, Canada",4 wins & 3 nominations.,https://m.media-amazon.com/images/M/MV5BN2YwNj...,9.5,"7,759",tt0356070
10,Final Fantasy VII,1997,T,07 Sep 1997,"Action, Adventure, Fantasy, Sci-Fi","Yoshinori Kitase, Yasushi Matsumura, Masato Ya...","Kazushige Nojima (story), Yoshinori Kitase (st...",NaN,A former soldier from an evil company joins a ...,"Japanese, English",Japan,2 wins & 3 nominations.,https://m.media-amazon.com/images/M/MV5BMGMxZD...,9.5,"9,001",tt0208155
11,Chrono Trigger,1995,NaN,22 Aug 1995,"Animation, Action, Adventure","Yoshinori Kitase, Akihiko Matsui, Takashi Tokita",Masato Kato (story),NaN,"Crono, a young boy, is thrust to adventure by ...","Japanese, English",Japan,NaN,https://m.media-amazon.com/images/M/MV5BNzc2Nz...,9.3,"1,657",tt0210613
12,The Elder Scrolls V: Skyrim,2011,M,11 Nov 2011,"Action, Adventure, Fantasy, Horror, Mystery, War","Todd Howard, Nick James Pearce","Emil Pagliarulo, Brian Chapin (writing), Jon P...","Max von Sydow, Christopher Plummer, Joan Allen...","After escaping execution, the last living Drag...",English,"USA, Australia",14 wins & 17 nominations.,https://m.media-amazon.com/images/M/MV5BYjlhNT...,9.4,"26,755",tt1814884
13,Mass Effect,2007,M,20 Nov 2007,"Action, Adventure, Sci-Fi",Casey Hudson,"Drew Karpyshyn (lead writer), Lukas Kristjanso...","Steven Barr, Kimberly Brooks, Keith David, Set...","In a technologically advanced future, an elite...",English,"USA, Canada",5 wins & 23 nominations.,https://m.media-amazon.com/images/M/MV5BNjE3MG...,9.2,"16,184",tt1073668
14,Grand Theft Auto: Vice City,2002,M,29 Oct 2002,"Action, Adventure, Crime, Drama","Marco Fernandez, Navid Khonsari","Dan Houser, James Worrall, Dan Houser (written...","Ray Liotta, William Fichtner, Tom Sizemore, De...","After being released from jail, Tommy Vercetti...","English, Spanish, Haitian, French","UK, USA, Austria",15 wins & 19 nominations.,https://m.media-amazon.com/images/M/MV5BYmIwZG...,9.2,"23,031",tt0314123
15,Mafia: The City of Lost Heaven,2002,M,29 Aug 2002,"Action, Crime, Drama, Thriller",Daniel Vávra,Daniel Vávra,"Michael Sorvino, William DeMeo, George DiCenzo...",You play a 1930s mobster as you act out your c...,"English, Czech, French, German, Italian, Spanish","Czech Republic, USA",2 nominations.,https://m.media-amazon.com/images/M/MV5BMzcwNT...,9.2,"5,297",tt0338221
16,Deus Ex,2000,M,22 Jun 2000,"Action, Mystery, Sci-Fi, Thriller",Warren Spector,"Sheldon Pacotti (dialogue), Austin Grossman (a...","Jay Anthony Franke, Brent Anderson, Ralph Barb...","In a dark cyberpunk future where poverty, dise...","English, French, Mandarin","USA, UK",1 win.,https://m.media-amazon.com/images/M/MV5BMWM4MD...,9.2,"2,932",tt0286585
17,Grim Fandango,1998,NaN,NaN,"Adventure, Comedy, Crime",Tim Schafer,"Eric Ingerson, Bret Mogilefsky, Tim Schafer, P...","Tony Plana, Maria Canals-Barrera, Alan Blumenf...",Manuel Calavera is a travel agent in The Land ...,"English, Spanish, Hungarian",USA,1 nomination.,NaN,9.0,"2,224",tt0177822
18,Elden Ring,2022,NaN,21 Jan 2022,"Action, Adventure, Fantasy",Hidetaka Miyazaki,George R.R. Martin,NaN,The game will transport players into a dark fa...,"Japanese, English",Japan,NaN,https://m.media-amazon.com/images/M/MV5BMTE3MG...,NaN,NaN,tt10562854
19,Metal Gear Solid 3: Snake Eater,2004,M,17 Nov 2004,"Action, Adventure, Crime, Mystery, Romance",Hideo Kojima,"Hideo Kojima (story), Hideo Kojima, Tomokazu F...","David Hayter, Suzetta Miñet, Jim Piddock, Heat...","In 1964, a U.S. government operative codenamed...",Japanese,Japan,2 nominations.,https://m.media-amazon.com/images/M/MV5BNzhlND...,9.5,"9,271",tt0365498
20,Grand Theft Auto: San Andreas,2004,M,26 Oct 2004,"Action, Adventure, Comedy, Crime",Navid Khonsari,"Dan Houser, James Worrall, DJ Pooh, James Worr...","Young Maylay, Faizon Love, Yolanda 'Yo-Yo' Whi...","A family tragedy prompts gangster Carl ""CJ"" Jo...","English, Spanish, German","UK, USA, France, Germany, Denmark, Hungary, Be...",6 wins & 12 nominations.,https://m.media-amazon.com/images/M/MV5BMTdkZD...,9.4,"35,019",tt0383385
21,Red Dead Redemption,2010,M,18 May 2010,"Action, Adventure, Crime, Drama, Western","Rod Edge, John Zurhellen","Dan Houser, Michael Unsworth, Christian Cantam...","Rob Wiethoff, Josh Blaylock, Sophia Marzocchi,...",A former outlaw is forced by the federal gover...,"English, Spanish, French, Cantonese, German","USA, UK, Canada",25 wins & 22 nominations.,https://m.media-amazon.com/images/M/MV5BZmYwNj...,9.5,"23,312",tt1479962
22,Batman: Arkham City,2011,T,18 Oct 2011,"Action, Adventure, Crime, Drama, Fantasy, Myst...",Sefton Hill,"Bob Kane (character created by: Batman), Paul ...","Carlos Alazraqui, Dee Bradley Baker, Troy Bake...",When part of Gotham is turned into a private r...,English,"UK, USA",17 wins & 28 nominations.,https://m.media-amazon.com/images/M/MV5BZDE2ZD...,9.4,"26,880",tt1568322
23,The Legend of Zelda: Breath of the Wild,2017,E10+,03 Mar 2017,"Action, Adventure, Fantasy","Hidemaro Fujibayashi, Hiroki Hirano, Kentaro T...",Akihito Toda (screenplay advisor),"Kengo Takanashi, Yû Shimamura, Kôji Takeda, No...","After a century of hibernation, Link reawakens...","Japanese, English","USA, Japan",8 wins & 12 nominations.,https://m.media-amazon.com/images/M/MV5BZTI3OT...,9.4,"5,083",tt3253986
24,Uncharted 2: Among Thieves,2009,T,13 Oct 2009,"Action, Adventure, Fantasy, Horror, Mystery, T...","Amy Hennig, Bruce Straley","Amy Hennig, Neil Druckmann, Josh Scherr","Nolan North, Emily Rose, Claudia Black, Richar...","After being tracked down by Harry Flynn, Natha...","Tibetan, English, Nepali",USA,30 wins & 16 nominations.,https://m.media-amazon.com/images/M/MV5BZDk4ZG...,9.4,"21,540",tt1349460
25,Portal 2,2011,NaN,19 Apr 2011,"Action, Adventure, Comedy",Joshua Weier,"Chet Faliszek, Ted Kosmatka, Jay Pinkerton, Er...","Ellen McLain, Stephen Merchant, J.K. Simmons, ...","Many years after ""Portal,"" Chell reawakens at ...",English,USA,9 wins & 8 nominations.,https://m.media-amazon.com/images/M/MV5BMTQ1MD...,9.5,"8,256",tt1648163
26,Half-Life 2,2004,M,16 Nov 2004,"Action, Adventure, Sci-Fi, Thriller",David Speyrer,Marc Laidlaw,"Robert Guillaume, Robert Culp, Louis Gossett J...","Dr. Freeman is taken out of stasis by his ""emp...","English, Russian",USA,28 wins & 13 nominations.,https://m.media-amazon.com/images/M/MV5BNzEwND...,9.4,"14,580",tt0374692
27,Mass Effect 3,2012,M,06 Mar 2012,"Action, Adventure, Sci-Fi",Casey Hudson,"John Dombrow (senior writer), Sylvia Feketekut...","Jennifer Hale, Mark Meer, Kimberly Brooks, Rap...",Earth is under attack by a monstrous race of g...,English,Canada,8 wins & 14 nominations.,https://m.media-amazon.com/images/M/MV5BYzg0OG...,9.1,"13,999",tt1839558

In [6]:
df1.to_csv("cleanedgamedata.csv")